spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    url:  ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
exchange:
  rate:
    api:
      key: ${EXCHANGE_RATE_API_KEY}
      url: ${EXCHANGE_RATE_API_URL:https://v6.exchangerate-api.com/v6}
    scheduler:
      # Runs every 5 hours at 5 minutes past the hour. (00:05, 05:05, 10:05, 15:05, 20:05)
      cron: 0 5 0/5 * * ?
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange_rate
    username: user1
    password: user1
  flyway:
    url: jdbc:postgresql://localhost:5432/exchange_rate
    user: user1
    password: user1
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#exchange:
#  rate:
#    scheduler:
#      # Runs every minute at the start of the minute. (e.g., 00:01, 00:02, ..., 23:59)
#      cron: 0 0/1 * * * ?