services:
  exchange-rate-db:
    image: postgres:16.4
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_ROOT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS='--auth-host=trust'
    ports:
      - 5432:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data