services:
  exchange-rate-service:
    image: @docker.repository.name@:@deployment.version@
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://exchange-rate-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_ROOT_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - SPRING_FLYWAY_URL=jdbc:postgresql://exchange-rate-db:5432/${POSTGRES_DB}
      - SPRING_FLYWAY_USER=${POSTGRES_ROOT_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
      - |
        JAVA_OPTS=
        -Dexchange.rate.scheduler.enabled=true
    depends_on:
      - exchange-rate-db